const pokemons = [
    {"name":"Cinderace", "role":"Attacker", "number": 815},
    {"name":"Garchomp", "role":"All around", "number": 445},
    {"name":"Gengar", "role":"Speedster", "number": 94},
    {"name":"Cramorent", "role":"Attacker", "number": 845},
    {"name":"Alola Ninetales", "role":"Attacker", "number": 38},
    {"name":"Wigllytuff", "role":"Supporter", "number": 40},
    {"name":"Machamp", "role":"All Around", "number": 68},
    {"name":"Absol", "role":"Speedster", "number": 359},
    {"name":"Slowbro", "role":"Defender", "number": 80},
    {"name":"Mr. Mime", "role":"Supporter", "number": 122},
    {"name":"Venusaur", "role":"Attacker", "number": 3},
    {"name":"Lucario", "role":"All Around", "number": 448},
    {"name":"Talonflame", "role":"Speedster", "number": 663},
    {"name":"Eldegoss", "role":"Supporter", "number": 830},
    {"name":"Greninja", "role":"Attacker", "number": 658},
    {"name":"Crustle", "role":"Defender", "number": 558},
    {"name":"Snorrlax", "role":"Defender", "number": 143},    
    {"name":"Charizard", "role":"All Around", "number": 6},
    {"name":"Pikachu", "role":"Attacker", "number": 25},
    {"name":"Zeraora", "role":"Speedster", "number": 807},
    {"name":"Gardevoir", "role":"Attacker", "number": 282},
    {"name":"Blissey", "role":"Supporter", "number": 242},
    {"name":"Blastoise", "role":"Defender", "number": 9},    
    {"name":"Mamoswine", "role":"Defender", "number": 473},    
    {"name":"Sylveon", "role":"Attacker", "number": 700},
    {"name":"Greedent", "role":"Defender", "number": 820},    
    {"name":"Decidueye", "role":"Attacker", "number": 724},
    {"name":"Tsareena", "role":"All Around", "number": 763},
    {"name":"Dragonite", "role":"All Around", "number": 149},    
]

export default pokemons